### ISSUE TITLE
UI布局

### ISSUE THREAD

**Issue by gongfuture** [AIKTV/ProjectUI#19]
# 基于python的ai语音处理界面
## 预计功能
 该项目功能为在ui界面上将录音或音频文件发送给**可供用户选择**的已经训练好的ai模型，电脑通过**脚本**的辅助自动跑模型合成处理好的ai音频文件并将其返回到可在ui界面显示的文件夹目录中，然后用户对其进行**播放**和**显示**音频等操作。
## 设计要求。
1. * 按钮1：选择ai模型。**（ gongfuture ）**
    * 按钮2：打开文件夹，选择未处理的音频文件。
    * 按钮3：使电脑录音（gyc)
    * 按钮4：播放音频文件（若文件在处理中，则显示**处理中...**)
    * 按钮5：打开文件夹，选择已处理的音频文件。
    * 按钮6：退出ui界面
2. * 进度条：显示播放进度 （ xiubi44 ）
3. * 文本框1：显示播放文件名称（若为录音文件则直接显示**录音**）(gongfuture)
    * 文本框2：显示播放文件总时间 （ xiubi44 ）
    * 文本框3：显示播放文件当前播放时间（文本框2和3中间加一个/）（ xiubi44 ）
    * 文本框4：显示选中模型路径（ gongfuture ）
    * 文本框5：录音计时(gyc)
4. * 图表1：显示未处理音频文件或录音的声波图
    * 图表2：显示已处理音频文件或录音的声波图
5.  * 脚本：自动选择步数，自动运行  （ fAx1A ）
## 参考
[Python Qt 简介 | 白月黑羽](https://www.byhy.net/tut/py/gui/qt_01/)
[QPushButton — Qt for Python --- QPushButton — 用于 Python 的 Qt](https://doc.qt.io/archives/qtforpython-5.12/PySide2/QtWidgets/QPushButton.html)
[QComboBox — Qt for Python](https://doc.qt.io/archives/qtforpython-5.12/PySide2/QtWidgets/QComboBox.html)
[pyqt school](https://www.w3schools.cn/pyqt5/pyqt5_whats_new.html)
[]()
年轻的**舰长**，**旅行者**，**开拓者**要学会分享好资源，好网站🤣
## 备注
  图表可能不需要，放最后做。处理好的文件和未处理文件是否需要保存与放置在哪个文件夹需商议，当多个模块后端相互联系时开发者需及时沟通或一人独揽（最好）。前端和后端需紧密配合，同步进行。文本框选择文件可以用控件（组合选择框）来代替（看需求）。有实力的可以用Qpainter自定义控件简化操作（极其推荐）。还需要有一名负责美工与装饰的开发者，会修改按钮，加入图画（最好会一点内嵌web浏览器），使ui界面流畅（比如调整播放条长度和采样率使其运作时不会太快和不卡顿；处理文件需要时间，所以加入一个显示**处理中**的按钮可以防止用户以为是卡顿）。最后助我们合作愉快😁😁😁
## **若有其它想法，请点击**编辑**在下面⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️填写建议**

**Comment by gongfuture** [comment]
所有关于ui变化的，请一律提交到UI-develop分支，以防造成ui文件冲突

**Comment by gongfuture** [comment]
UI谁来写啊

**Comment by jianghuaiX** [comment]
基于python的ai语音处理界面
一.预计功能
该项目功能为在ui界面上将录音或音频文件发送给可供用户选择的已经训练好的ai模型，电脑通过脚本的辅助自动跑模型合成处理好的ai音频文件并将其返回到可在ui界面显示的文件夹目录中，然后用户对其进行播放和显示音频等操作。
二.设计要求。
1.  按钮1：选择ai模型。
     按钮2：选择未处理的音频文件。

**Comment by gongfuture** [comment]
你这UI的id和文档里都对不上？

**Comment by gongfuture** [comment]
> 你这UI的id和文档里都对不上？ @jianghuaiX

按钮4对应pushButton_7，文本框3对应lineEdit_1？怎么写的文档啊？

**Comment by gongfuture** [comment]
显示选中模型路径的控件请求更改为ComboBox
